version: 2.1.1
last_compiled: 2026-01-08 17:55:10

# ================================================
# Compiled with the following settings:
#
# To change these settings, run ~/agent-os/scripts/project-update.sh to re-compile your project with the new settings.
# ================================================
profile: default
claude_code_commands: true
use_claude_code_subagents: false
agent_os_commands: true
standards_as_claude_code_skills: true
